/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mqstack_ffmpegjni_FFmpegJni */

#ifndef _Included_org_mqstack_ffmpegjni_FFmpegJni
#define _Included_org_mqstack_ffmpegjni_FFmpegJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mqstack_ffmpegjni_FFmpegJni
 * Method:    run
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_smackall_animator_FFmpeg_run(JNIEnv *env, jobject obj, jint argc, jobjectArray args);

#ifdef __cplusplus
}
#endif
#endif
